export const COLORS = {
  us: '#315bcf',
  ussr: '#d14949',
  china: '#d14949',
  north: '#315bcf',
  france: '#315bcf',
  australia: '#d14949',
  southAmerica: '#315bcf',
  abyss: '#d14949',
  datum: '#f4fff1',
};

export const NETWORKS = {
  us: { label: '美国南极测绘局', color: COLORS.us },
  ussr: { label: '内陆特别作业局', color: COLORS.ussr },
  china: { label: '昆仑工程', color: COLORS.china },
  north: { label: '北方联合委员会', color: COLORS.north },
  france: { label: '法国极地项目', color: COLORS.france },
  australia: { label: '澳新运输协作网', color: COLORS.australia },
  southAmerica: { label: '南美条约观察网', color: COLORS.southAmerica },
};

export const RESEARCH_STATIONS = [
  ['US-MCM', '麦克默多站', 'McMurdo Station', 'us', -77.85, 166.6667, '海岸后勤母站'],
  ['US-SP', '阿蒙森—斯科特南极点站', 'Amundsen–Scott South Pole Station', 'us', -89.9833, 0, '内陆航空／气象站'],
  ['US-BYD', '伯德站', 'Byrd Station', 'us', -80.0167, -119.5333, '内陆地球物理站'],
  ['SU-MIR', '和平站', 'Mirny Station', 'ussr', -66.5532, 93.0096, '海岸后勤母站'],
  ['SU-VOS', '东方站', 'Vostok Station', 'ussr', -78.4642, 106.8369, '中央高原站'],
  ['SU-NOV', '新拉扎列夫站', 'Novolazarevskaya Station', 'ussr', -70.7758, 11.8322, '西部海岸—内陆接口'],
  ['UK-HAL', '哈雷湾站', 'Halley Bay Station', 'north', -75.5167, -26.65, '冰架观测／监听站'],
  ['UK-SIG', '锡格尼站', 'Signy Station', 'north', -60.7083, -45.5954, '海洋与生物站'],
  ['UK-F', 'F站／阿根廷群岛站', 'Station F / Argentine Islands', 'north', -65.2457, -64.2575, '地球物理监听站'],
  ['UK-D', 'D站／希望湾', 'Station D / Hope Bay', 'north', -63.4, -57, '档案与人员转接站'],
  ['FR-DDU', '迪蒙·迪维尔站', "Dumont d’Urville Station", 'france', -66.6628, 140.0013, '海岸科研母站'],
  ['FR-CHA', '夏尔科旧站', 'Former Charcot Station', 'france', -69.3667, 139.0167, '旧内陆站'],
  ['AU-MAW', '莫森站', 'Mawson Station', 'australia', -67.6026, 62.873, '海岸后勤母站'],
  ['AU-DAV', '戴维斯站', 'Davis Station', 'australia', -68.5759, 77.9695, '海岸—高原接口'],
  ['AU-WIL', '威尔克斯站', 'Wilkes Station', 'australia', -66.2533, 110.5317, '东部海岸站'],
  ['NZ-SCO', '斯科特基地', 'Scott Base', 'australia', -77.8494, 166.7673, '罗斯海中转站'],
  ['AR-ORC', '奥卡达斯站', 'Orcadas Base', 'southAmerica', -60.7376, -44.7374, '长期气象站'],
  ['AR-ESP', '埃斯佩兰萨站', 'Esperanza Base', 'southAmerica', -63.397, -56.9981, '半岛前沿站'],
  ['CL-PRT', '阿图罗·普拉特站', 'Arturo Prat Base', 'southAmerica', -62.4787, -59.6636, '海军气象站'],
  ['CL-OHI', '奥希金斯站', "General Bernardo O’Higgins Base", 'southAmerica', -63.321, -57.8998, '半岛常驻站'],
].map(([code, name, english, network, lat, lng, type]) => ({
  code,
  name,
  english,
  network,
  operator: NETWORKS[network].label,
  color: NETWORKS[network].color,
  lat,
  lng,
  type,
  status: '同期档案有效',
  role: `${type}；承担白幕行动的公开后勤、监听或档案掩护。`,
}));

export const ABYSS_POINTS = [
  ['US-K1', '雁背竖井', 'us', -86.2, 34, 'B级人员货运井'],
  ['US-K2', '蓝阶斜道', 'us', -84, 42, 'A级重型入口'],
  ['US-K4', '地平线通风井', 'us', -87.8, 80, 'E级应急通道'],
  ['US-K7', '回声探井', 'us', -85.2, 70, 'D级仪器探井'],
  ['SU-D1', '曙光一号货运井', 'ussr', -79, 101.5, 'B级人员货运井'],
  ['SU-D3', '红坡道', 'ussr', -80.3, 119, 'A级重型入口'],
  ['SU-D6', '湖钟探口', 'ussr', -77.5, 118, 'D级水文探井'],
  ['SU-Z9', '西线九号井', 'ussr', -83.3, 103, 'E级争议通道'],
  ['CN-KL1', '昆仑一号旧井线', 'china', -80.4, 68, 'C级阶梯井'],
  ['CN-SL2', '松岭裂口', 'china', -82.5, 57, 'C级天然裂隙'],
  ['CN-RS3', '红签探井', 'china', -81, 87, 'D级小径探井'],
  ['CN-HY0', '海燕中转点', 'china', -78, 80, '地表支援节点'],
  ['NC-N1', '南森门', 'north', -79, 18.5, 'C级冻结河洞'],
  ['NC-T2', '塔巴林吊舱井', 'north', -81, 28.7, 'C级单人吊舱井'],
  ['NC-L3', '圣露西陷口', 'north', -82.8, 13.5, 'E级季节冰漏斗'],
  ['FR-C1', '夏尔科斜廊', 'france', -77.9, 140, 'C级蓝冰裂谷斜道'],
  ['FR-O2', '奥尔菲探井', 'france', -80.2, 134, 'D级影像探井'],
  ['AU-W1', '威尔克斯湿门', 'australia', -75.3, 70.5, 'C级半淹没冰洞'],
  ['BZ-00', '白幕名义中心', 'datum', -81.7667, 75.15, '联合地图基准'],
].map(([code, name, network, lat, lng, type]) => ({
  code,
  name,
  network,
  operator: network === 'datum' ? '多国联合核定' : NETWORKS[network].label,
  color: network === 'datum' ? COLORS.datum : NETWORKS[network].color,
  lat,
  lng,
  type,
  status: code === 'BZ-00' ? '联合核定有效' : '限制访问',
  role: code === 'BZ-00' ? 'PALIS联合坐标基准；不对应单一可见入口。' : '入口依赖地表科考站、雪道与无线电网络维持。',
  datum: code === 'BZ-00',
}));

export const LOGISTICS_ROUTES = [
  { network: 'us', nodes: ['US-MCM', 'US-SP', 'US-K4', 'US-K1', 'US-K2'] },
  { network: 'us', nodes: ['US-SP', 'US-K7'] },
  { network: 'ussr', nodes: ['SU-MIR', 'SU-VOS', 'SU-D1', 'SU-D6'] },
  { network: 'ussr', nodes: ['SU-VOS', 'SU-D3', 'SU-Z9'] },
  { network: 'china', nodes: ['SU-VOS', 'CN-HY0', 'CN-RS3', 'CN-KL1', 'CN-SL2'] },
  { network: 'north', nodes: ['UK-HAL', 'NC-N1', 'NC-T2', 'NC-L3'] },
  { network: 'france', nodes: ['FR-DDU', 'FR-CHA', 'FR-C1', 'FR-O2'] },
  { network: 'australia', nodes: ['AU-DAV', 'AU-W1'] },
];

export const ARCHIVES = [
  {
    id: 'overview',
    code: '01',
    name: '项目总览',
    file: 'WHITE_ABYSS_OVERVIEW.TXT',
    meta: '7 FILES / EARLY ARCHIVE',
    heading: '世界在南极冰层下方继续。',
    body: [
      '白幕并非单一洞穴，而是一块未能闭合的地下世界。地表入口分散在南极高原，由多国科考站、运输线与保密体系共同维持。',
      '本终端收录战后早期的核定坐标、事件档案、任务影像与阵营记录。所有时间、距离和人员状态均以档案版本为准。',
    ],
    stats: [['档案时期', '战后早期'], ['核定入口', '19'], ['关联站点', '20']],
  },
  {
    id: 'world',
    code: '02',
    name: '世界观设定',
    file: 'WORLD_RULES.SYS',
    meta: '12 FILES / READ ONLY',
    heading: '闭合失败，是这里唯一稳定的规律。',
    body: [
      '白幕会复制路线、延迟状态，并把观察者的记忆写入地形。地图不是对空间的描述，而是一份短期有效的协定。',
      '档案包含地理生态、异常总则、主要阵营、全球保密体系与西线主线事件。',
    ],
    stats: [['异常类型', '08'], ['主要阵营', '07'], ['公开认知', 'LOW']],
  },
  {
    id: 'events',
    code: '03',
    name: '事件档案',
    file: 'INCIDENT_INDEX.DAT',
    meta: '3 FILES / CLASSIFIED',
    heading: '1952：HZ-6 样本线没有按原路返回。',
    body: [
      '一支五人测绘队沿 HZ-6 样本线进入针叶林。无线电记录显示，他们在停止前进后仍持续远离营地。',
      '现存材料包括中文译本、英文原件与任务记录；文件间的差异被视为事件本身的一部分。',
    ],
    stats: [['幸存人员', '05'], ['胶卷', '20'], ['路线状态', 'UNCLOSED']],
  },
  {
    id: 'missions',
    code: '04',
    name: '任务档案',
    file: 'HZ6_MISSION.LOG',
    meta: 'REPORT / PHOTO / VOICE',
    heading: '任务编号 HZ-6 / R06。',
    body: [
      '人员、照片、任务报告与视频配音稿被绑定为同一证据链。任何单独抽离的图像都不足以证明路线曾经存在。',
      '照片按胶卷顺序排列，保留欠曝、结露、叠片和运动模糊，不做现代化修复。',
    ],
    stats: [['人员', '05'], ['照片', '20'], ['证据链', 'LOCKED']],
  },
  {
    id: 'visuals',
    code: '05',
    name: '视觉素材',
    file: 'VISUAL_ASSETS.IDX',
    meta: 'MAP / STAMP / FILM',
    heading: '看见不等于确认。',
    body: [
      '概念视觉、南极地形图、透明档案印章与 HZ-6 尼康胶片共同构成白幕的视觉证据系统。',
      '所有素材遵循低饱和、年代一致与来源可追溯原则；异常只出现在本该正常的位置。',
    ],
    stats: [['概念图', '07+'], ['透明素材', 'EN'], ['视觉状态', 'VERIFIED']],
  },
];
