// 1964 story-time reference layer.
// Selection follows 02_世界观设定/09_全球科考站网络.md: only public
// stations that form the White Abyss logistics, cover, listening or treaty network.
export const RESEARCH_STATIONS = [
  {
    code: 'US-MCM',
    name: '麦克默多站',
    english: 'McMurdo Station',
    operator: '美国',
    network: '美国南极测绘局',
    lat: -77.85,
    lng: 166.6667,
    status: '1964年常年运行',
    type: '海岸后勤母站',
    role: '航空、影像冲洗、人员与档案总接口；BAS需求被拆入公开项目账目。',
  },
  {
    code: 'US-SP',
    name: '阿蒙森—斯科特南极点站',
    english: 'Amundsen–Scott South Pole Station',
    operator: '美国',
    network: '美国南极测绘局',
    lat: -89.9833,
    lng: 0,
    status: '1964年常年运行',
    type: '内陆航空／气象站',
    role: '白幕南部测线和人员转运支点，也是异常航迹最常用的公开解释。',
  },
  {
    code: 'US-BYD',
    name: '伯德站',
    english: 'Byrd Station',
    operator: '美国',
    network: '美国南极测绘局',
    lat: -80.0167,
    lng: -119.5333,
    status: '1964年常年运行',
    type: '内陆地球物理站',
    role: '地震测深、冰盖钻探与承包合同掩护；承担白幕项目的账目分流。',
  },
  {
    code: 'SU-MIR',
    name: '和平站',
    english: 'Mirny Station',
    operator: '苏联',
    network: '内陆特别作业局',
    lat: -66.5532,
    lng: 93.0096,
    status: '1964年常年运行',
    type: '海岸后勤母站',
    role: '苏联东南极船运与履带车出发点，重型井口设备以公开内陆考察名义入境。',
  },
  {
    code: 'SU-VOS',
    name: '东方站',
    english: 'Vostok Station',
    operator: '苏联',
    network: '内陆特别作业局',
    lat: -78.4642,
    lng: 106.8369,
    status: '1964年常年运行',
    type: '中央高原站',
    role: '白幕东部湖链的主要参照点和最重要的地震测深资料接口。',
  },
  {
    code: 'SU-NOV',
    name: '新拉扎列夫站',
    english: 'Novolazarevskaya Station',
    operator: '苏联',
    network: '内陆特别作业局',
    lat: -70.7758,
    lng: 11.8322,
    status: '1964年常年运行',
    type: '西部海岸—内陆接口',
    role: '承担大西洋方向人员、无线电与替代运输线，降低和平站单线暴露风险。',
  },
  {
    code: 'UK-HAL',
    name: '哈雷湾站',
    english: 'Halley Bay Station',
    operator: '英国',
    network: '北方联合委员会',
    lat: -75.5167,
    lng: -26.65,
    status: '1964年常年运行',
    type: '冰架观测／监听站',
    role: '记录长波、极光与异常授时信号，为委员会提供跨大陆监听基线。',
  },
  {
    code: 'UK-SIG',
    name: '锡格尼站',
    english: 'Signy Station',
    operator: '英国',
    network: '北方联合委员会',
    lat: -60.7083,
    lng: -45.5954,
    status: '1964年季节运行',
    type: '海洋与生物站',
    role: '承担样本转签、无线电抄收与不进入中央高原的外围人员安置。',
  },
  {
    code: 'UK-F',
    name: 'F站／阿根廷群岛站',
    english: 'Station F / Argentine Islands',
    operator: '英国',
    network: '北方联合委员会',
    lat: -65.2457,
    lng: -64.2575,
    status: '1964年常年运行',
    type: '地球物理监听站',
    role: '以电离层与地磁观测掩护对白幕通信时差和重复呼号的长期归档。',
  },
  {
    code: 'UK-D',
    name: 'D站／希望湾',
    english: 'Station D / Hope Bay',
    operator: '英国',
    network: '北方联合委员会',
    lat: -63.4,
    lng: -57.0,
    status: '1964年撤站节点',
    type: '档案与人员转接站',
    role: '撤站过程被委员会用于转移旧档案、身份记录和少量封存样本。',
  },
  {
    code: 'FR-DDU',
    name: '迪蒙·迪维尔站',
    english: "Dumont d'Urville Station",
    operator: '法国',
    network: '法国极地项目',
    lat: -66.6628,
    lng: 140.0013,
    status: '1964年常年运行',
    type: '海岸科研母站',
    role: '人员与胶片入口；以植物分类、冰川和纪录片项目覆盖林缘站往来。',
  },
  {
    code: 'FR-CHA',
    name: '夏尔科旧站',
    english: 'Former Charcot Station',
    operator: '法国',
    network: '法国极地项目',
    lat: -69.3667,
    lng: 139.0167,
    status: '1960年关闭／1964年仍作旧线基准',
    type: '旧内陆站',
    role: '废弃设施、旧里程和积雪层位被继续用作夏尔科斜廊运输线的档案锚点。',
  },
  {
    code: 'AU-MAW',
    name: '莫森站',
    english: 'Mawson Station',
    operator: '澳大利亚',
    network: '澳新运输协作网',
    lat: -67.6026,
    lng: 62.873,
    status: '1964年常年运行',
    type: '海岸后勤母站',
    role: '西侧测绘队、油料和路线杆系统的主要来源。',
  },
  {
    code: 'AU-DAV',
    name: '戴维斯站',
    english: 'Davis Station',
    operator: '澳大利亚',
    network: '澳新运输协作网',
    lat: -68.5759,
    lng: 77.9695,
    status: '1964年常年运行',
    type: '海岸—高原接口',
    role: '最接近白幕北向扇区的公开澳方节点，承担测绘营与中继物资。',
  },
  {
    code: 'AU-WIL',
    name: '威尔克斯站',
    english: 'Wilkes Station',
    operator: '澳大利亚',
    network: '澳新运输协作网',
    lat: -66.2533,
    lng: 110.5317,
    status: '1964年常年运行',
    type: '东部海岸站',
    role: 'AU-W1湿门的公开运输外壳；旧美制设施造成档案归属和箱号混杂。',
  },
  {
    code: 'NZ-SCO',
    name: '斯科特基地',
    english: 'Scott Base',
    operator: '新西兰',
    network: '澳新运输协作网',
    lat: -77.8494,
    lng: 166.7673,
    status: '1964年常年运行',
    type: '罗斯海中转站',
    role: '为小型测绘队提供气象、车辆和人员中转，也观察美国航线的异常偏移。',
  },
  {
    code: 'AR-ORC',
    name: '奥卡达斯站',
    english: 'Orcadas Base',
    operator: '阿根廷',
    network: '南美条约观察网',
    lat: -60.7376,
    lng: -44.7374,
    status: '1964年常年运行',
    type: '长期气象站',
    role: '为南美国家提供独立气象记录，用于质疑被美苏改写的大陆尺度天气与时间线。',
  },
  {
    code: 'AR-ESP',
    name: '埃斯佩兰萨站',
    english: 'Esperanza Base',
    operator: '阿根廷',
    network: '南美条约观察网',
    lat: -63.397,
    lng: -56.9981,
    status: '1964年常年运行',
    type: '半岛前沿站',
    role: '保存希望湾地区的第二套地名、无线电和人员记录。',
  },
  {
    code: 'CL-PRT',
    name: '阿图罗·普拉特站',
    english: 'Arturo Prat Base',
    operator: '智利',
    network: '南美条约观察网',
    lat: -62.4787,
    lng: -59.6636,
    status: '1964年常年运行',
    type: '海军气象站',
    role: '以海军电台截获公开航行通告，与白幕项目伪造的运输时间发生冲突。',
  },
  {
    code: 'CL-OHI',
    name: '奥希金斯站',
    english: "General Bernardo O'Higgins Base",
    operator: '智利',
    network: '南美条约观察网',
    lat: -63.321,
    lng: -57.8998,
    status: '1964年常年运行',
    type: '半岛常驻站',
    role: '与英阿站点形成重叠监听区，让同一呼号常被三套档案同时记录。',
  },
];
